POST https://localhost:8000/api/fibonacci/
Accept: application/json
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="lower_limit"

1234
--WebAppBoundary
Content-Disposition: form-data; name="upper_limit"

12345
--WebAppBoundary--

###